version: '3'
services:
  mysql:
    image: mysql:5.6
    command: 
      - mysqldmysqld
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment: 
      MYSQL_DATABASE: jingsaas
      MYSQL_USER: jingfree
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd
    ports: 
      - "3306:3306"
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
  php-fpm:
    build: php
    #mage: larryz/php-fpm-composer:1.1
    links: 
      - mysql
      - redis
    ports:
      - "9000:9000"
    volumes: 
      - "../jing-saas/:/var/www/html"
    
  nginx:
    image: nginx:alpine
    links: 
      - php-fpm
    depends_on: 
      - redis
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - "./nginx/log:/var/log/nginx"
      - "./nginx/sites-available:/etc/nginx/sites-available"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../jing-saas/:/var/www/html"