version: '3'
services:
  parse-server-android:
    #build: .
    image: parseplatform/parse-server
    ports:
      - "1337:1337"
    
    environment:
      PARSE_SERVER_APPLICATION_ID: jingfree_android
      PARSE_SERVER_MASTER_KEY: aa9YOWvTxxCY2RXT
      PARSE_SERVER_DATABASE_URI: mongodb://mongo:27017/parse
      PARSE_SERVER_CLIENT_KEY: jingfree_android
      PARSE_SERVER_JAVASCRIPT_KEY: jingfree_android
    links:
      - mongo
  parse-server-web:
    #build: .
    image: parseplatform/parse-server
    ports:
      - "2337:1337"
    
    environment:
      PARSE_SERVER_APPLICATION_ID: jingfree_web
      PARSE_SERVER_MASTER_KEY: 6aXXk4Oask7rFTLM
      PARSE_SERVER_DATABASE_URI: mongodb://mongo:27017/parse_server_web
      PARSE_SERVER_CLIENT_KEY: jingfree_web
      PARSE_SERVER_JAVASCRIPT_KEY: jingfree_web
    links:
      - mongo

  parse-dashboard:
    image: parseplatform/parse-dashboard:1.0.22
    #image: yongjhih/parse-dashboard

    environment:
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
    volumes:
      - "./parse/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json"
    ports:
      - "4040:4040"
    entrypoint:  
      - npm
      - run
      - dashboard
