version: '3'
services:
  parse-server:
    #build: .
    image: parseplatform/parse-server
    ports:
      - "1337:1337"
    
    environment:
      PARSE_SERVER_APPLICATION_ID: jingfree
      PARSE_SERVER_MASTER_KEY: jingfree
      PARSE_SERVER_DATABASE_URI: mongodb://mongo:27017/jingfree
      PARSE_SERVER_CLIENT_KEY: jingfree
      PARSE_SERVER_JAVASCRIPT_KEY: jingfree
    links:
      - mongo

  parse-dashboard:
    image: parseplatform/parse-dashboard:1.0.22
    #image: yongjhih/parse-dashboard
    links:
      - parse-server
    environment:
      appId: jingfree 
      masterKey: jingfreejingfree
      serverURL: https://localhost:1337/parse
      PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1
    volumes:
      - "./parse/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json"
    ports:
      - "4040:4040"
    entrypoint:  
      - npm
      - run
      - dashboard
