version: '3'
services:
  node-cms-dev:
    image: registry.cn-hangzhou.aliyuncs.com/homehub/jingnode:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - "../jing-saas/jingcms:/usr/src/app"
    command:
      # - top
      - sh
      - -c
      - "npm install && nodemon -L --exec npm run dev"

