version: '3'
services:
  mysql:
    image: mysql:5.6
    command:
      - mysqld
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      - MYSQL_DATABASE=jingsaas
      - MYSQL_USER=jingfree
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_ROOT_PASSWORD=passw0rd
      - TZ="Asia/Shanghai"
    ports:
      - "43306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d"
  mongo:
    image: mongo:3.4.2
    command:
      - mongod
    ports:
      - "47017:27017"
    volumes:
      - "./mongo/data:/data/db"
  redis:
    image: redis:alpine
    ports:
      - "46379:6379"
  php-fpm:
    image: registry.cn-hangzhou.aliyuncs.com/homehub/jingdocker:1.8.6
    links:
      - mysql
      - redis
      - mongo
    env_file:
      - ./php/jingsaas.env
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - "../jing-saas/supervisor/:/etc/supervisor.d"
      - "../jing-saas/:/var/www/html"
      - "../piwik/:/var/www/piwik"
      - "../freecart/:/var/www/freecart"
      - "../jingweb/:/var/www/jingweb"
  php-publication:
    image: registry.cn-hangzhou.aliyuncs.com/homehub/jingdocker:1.8.6
    links:
      - mysql
      - redis
      - mongo
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - "../xingstation-publication/supervisor:/etc/supervisor.d"
      - "../xingstation-publication/:/var/www/html"
  php-api:
    image: registry.cn-hangzhou.aliyuncs.com/homehub/jingdocker:1.8.6
    links:
      - mysql
      - redis
    cap_add:
      - "SYS_PTRACE"
    volumes:
      - "../xingstation-api/supervisor:/etc/supervisor.d"
      - "../xingstation-api/:/var/www/html"
  openresty:
    image: openresty/openresty:xenial
    links:
      - php-fpm
      - php-publication
      - php-api
    depends_on:
      - redis
      - php-fpm
      - php-publication
      - php-api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/logs:/usr/local/openresty/nginx/logs"
      - "./nginx/conf:/usr/local/openresty/nginx/conf"
      - "./nginx/cert/newgls:/usr/local/openresty/nginx/cert/"
      - "../jing-saas/:/var/www/html"
      - "../piwik/:/var/www/piwik"
      - "../freecart/:/var/www/freecart"
      - "../jingweb/:/var/www/jingweb"
      - "../xingstation_activity/:/var/www/xingstation_activity"
      - "../xingstation-api/:/var/www/xingstation-api"
      - "../xingstation-publication/:/var/www/xingstation-publication"
      - "../xingstation-web/:/var/www/xingstation-web"
    environment:
      - SERVER_NAME


