version: '3'
services:
  node-h5-dev:
    image: registry.cn-hangzhou.aliyuncs.com/homehub/jingnode:1.0.0
    ports:
      - "8087:8087"
    volumes:
      - "../xingstation_activity:/usr/src/app"
    command:
      # - top
      - sh
      - -c
      - "npm install && nodemon -L --exec npm run dev"