version: '2'

services:
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/homehub/elasticsearch:5.4.3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: registry.cn-hangzhou.aliyuncs.com/homehub/logstash:5.4.3
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ../nginx/log/access.log:/logstash/nginx-access.log
      - ./logstash/pattern:/pattern
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: registry.cn-hangzhou.aliyuncs.com/homehub/kibana:5.4.3
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
